//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sewing
    {
        public int SewingID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> SewingStart { get; set; }
        public Nullable<System.DateTime> SewingEnd { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
